name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.16.2'
        otp-version: '26.2'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y sqlite3 libsqlite3-dev nodejs npm

    - name: Install dependencies
      run: mix deps.get

    - name: Check code format
      run: mix format --check-formatted

    - name: Compile
      run: mix compile --warnings-as-errors

    - name: Run tests
      run: mix test
